package com.stkiller.idea.reviewplugin.settings;

import java.awt.Dimension;
import java.awt.Insets;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import com.intellij.openapi.options.Configurable;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.Nullable;

/**
 * @author andrei (10/12/2012)
 */
public class ReviewAidSettings implements Configurable {

    private final ReviewAidSettingsHolder settingsHolder;
    private JPanel generalPanel;
    private JTextArea formatArea;


    public ReviewAidSettings() {
        $$$setupUI$$$();
        settingsHolder = ReviewAidSettingsHolder.getInstance();
    }


    @Nls
    @Override
    public String getDisplayName() {
        return "Review Aid";
    }


    @Nullable
    @Override
    public String getHelpTopic() {
        return null;
    }


    @Nullable
    @Override
    public JComponent createComponent() {
        reset();
        return generalPanel;
    }


    @Override
    public boolean isModified() {
        return !settingsHolder.OUTPUT_FORMAT_REGEX.equals(formatArea.getText());
    }


    @Override
    public void apply() throws ConfigurationException {
        settingsHolder.OUTPUT_FORMAT_REGEX = formatArea.getText();
    }


    @Override
    public void reset() {
        formatArea.setText(settingsHolder.OUTPUT_FORMAT_REGEX);
    }


    @Override
    public void disposeUIResources() {
    }


    private void createUIComponents() {
        generalPanel = new JPanel();
        formatArea = new JTextArea();
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        generalPanel.setLayout(new GridLayoutManager(3, 1, new Insets(5, 5, 5, 5), -1, -1));
        generalPanel.setAutoscrolls(false);
        final JTextArea textArea1 = new JTextArea();
        textArea1.setEditable(false);
        textArea1.setEnabled(true);
        textArea1.setText(
                "There you can specify the format of reject resons.\nThe available variables are :\n%1$s - class/file name.\n%2$s - selested variable/element name.\n%3$s - line number.\n%4$s - provided comment");
        generalPanel.add(textArea1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                        GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(150, 100), null, 0,
                                                        false));
        final JScrollPane scrollPane1 = new JScrollPane();
        generalPanel.add(scrollPane1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
                                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
                                                          null, null, null, 0, false));
        formatArea.setLineWrap(false);
        formatArea.setText("");
        scrollPane1.setViewportView(formatArea);
        final JLabel label1 = new JLabel();
        label1.setText("Please specify format");
        generalPanel.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                     GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null,
                                                     0, false));
    }


    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return generalPanel;
    }
}
